// Code generated by 'go generate'; DO NOT EDIT.

package time

import (
	"strconv"

	"github.com/topxeq/charlang"
)

// funcPTROEx is a generated function to make charlang.CallableExFunc.
// Source: funcPTRO(t *Time) (ret charlang.Object)
func funcPTROEx(fn func(*Time) charlang.Object) charlang.CallableExFunc {
	return func(args charlang.Call) (ret charlang.Object, err error) {
		if err := args.CheckLen(1); err != nil {
			return charlang.Undefined, err
		}

		t, ok := ToTime(args.Get(0))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args.Get(0).TypeName())
		}

		ret = fn(t)
		return
	}
}

// funcPTi64ROEx is a generated function to make charlang.CallableExFunc.
// Source: funcPTi64RO(t *Time, d int64) (ret charlang.Object)
func funcPTi64ROEx(fn func(*Time, int64) charlang.Object) charlang.CallableExFunc {
	return func(args charlang.Call) (ret charlang.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return charlang.Undefined, err
		}

		t, ok := ToTime(args.Get(0))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args.Get(0).TypeName())
		}
		d, ok := charlang.ToGoInt64(args.Get(1))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "int", args.Get(1).TypeName())
		}

		ret = fn(t, d)
		return
	}
}

// funcPTTROEx is a generated function to make charlang.CallableExFunc.
// Source: funcPTTRO(t1 *Time, t2 *Time) (ret charlang.Object)
func funcPTTROEx(fn func(*Time, *Time) charlang.Object) charlang.CallableExFunc {
	return func(args charlang.Call) (ret charlang.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return charlang.Undefined, err
		}

		t1, ok := ToTime(args.Get(0))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args.Get(0).TypeName())
		}
		t2, ok := ToTime(args.Get(1))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "time", args.Get(1).TypeName())
		}

		ret = fn(t1, t2)
		return
	}
}

// funcPTiiiROEx is a generated function to make charlang.CallableExFunc.
// Source: funcPTiiiRO(t *Time, i1 int, i2 int, i3 int) (ret charlang.Object)
func funcPTiiiROEx(fn func(*Time, int, int, int) charlang.Object) charlang.CallableExFunc {
	return func(args charlang.Call) (ret charlang.Object, err error) {
		if err := args.CheckLen(4); err != nil {
			return charlang.Undefined, err
		}

		t, ok := ToTime(args.Get(0))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args.Get(0).TypeName())
		}
		i1, ok := charlang.ToGoInt(args.Get(1))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "int", args.Get(1).TypeName())
		}
		i2, ok := charlang.ToGoInt(args.Get(2))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("3rd", "int", args.Get(2).TypeName())
		}
		i3, ok := charlang.ToGoInt(args.Get(3))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("4th", "int", args.Get(3).TypeName())
		}

		ret = fn(t, i1, i2, i3)
		return
	}
}

// funcPTsROEx is a generated function to make charlang.CallableExFunc.
// Source: funcPTsRO(t *Time, s string) (ret charlang.Object)
func funcPTsROEx(fn func(*Time, string) charlang.Object) charlang.CallableExFunc {
	return func(args charlang.Call) (ret charlang.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return charlang.Undefined, err
		}

		t, ok := ToTime(args.Get(0))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args.Get(0).TypeName())
		}
		s, ok := charlang.ToGoString(args.Get(1))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "string", args.Get(1).TypeName())
		}

		ret = fn(t, s)
		return
	}
}

// funcPTb2sROEx is a generated function to make charlang.CallableExFunc.
// Source: funcPTb2sRO(t *Time, b []byte, s string) (ret charlang.Object)
func funcPTb2sROEx(fn func(*Time, []byte, string) charlang.Object) charlang.CallableExFunc {
	return func(args charlang.Call) (ret charlang.Object, err error) {
		if err := args.CheckLen(3); err != nil {
			return charlang.Undefined, err
		}

		t, ok := ToTime(args.Get(0))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args.Get(0).TypeName())
		}
		b, ok := charlang.ToGoByteSlice(args.Get(1))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "bytes", args.Get(1).TypeName())
		}
		s, ok := charlang.ToGoString(args.Get(2))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("3rd", "string", args.Get(2).TypeName())
		}

		ret = fn(t, b, s)
		return
	}
}

// funcPTLROEx is a generated function to make charlang.CallableExFunc.
// Source: funcPTLRO(t *Time, loc *Location) (ret charlang.Object)
func funcPTLROEx(fn func(*Time, *Location) charlang.Object) charlang.CallableExFunc {
	return func(args charlang.Call) (ret charlang.Object, err error) {
		if err := args.CheckLen(2); err != nil {
			return charlang.Undefined, err
		}

		t, ok := ToTime(args.Get(0))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args.Get(0).TypeName())
		}
		loc, ok := ToLocation(args.Get(1))
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "location", args.Get(1).TypeName())
		}

		ret = fn(t, loc)
		return
	}
}

// funcPTRO is a generated function to make charlang.CallableFunc.
// Source: funcPTRO(t *Time) (ret charlang.Object)
func funcPTRO(fn func(*Time) charlang.Object) charlang.CallableFunc {
	return func(args ...charlang.Object) (ret charlang.Object, err error) {
		if len(args) != 1 {
			return charlang.Undefined, charlang.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		t, ok := ToTime(args[0])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args[0].TypeName())
		}

		ret = fn(t)
		return
	}
}

// funcPTi64RO is a generated function to make charlang.CallableFunc.
// Source: funcPTi64RO(t *Time, d int64) (ret charlang.Object)
func funcPTi64RO(fn func(*Time, int64) charlang.Object) charlang.CallableFunc {
	return func(args ...charlang.Object) (ret charlang.Object, err error) {
		if len(args) != 2 {
			return charlang.Undefined, charlang.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		t, ok := ToTime(args[0])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args[0].TypeName())
		}
		d, ok := charlang.ToGoInt64(args[1])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "int", args[1].TypeName())
		}

		ret = fn(t, d)
		return
	}
}

// funcPTTRO is a generated function to make charlang.CallableFunc.
// Source: funcPTTRO(t1 *Time, t2 *Time) (ret charlang.Object)
func funcPTTRO(fn func(*Time, *Time) charlang.Object) charlang.CallableFunc {
	return func(args ...charlang.Object) (ret charlang.Object, err error) {
		if len(args) != 2 {
			return charlang.Undefined, charlang.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		t1, ok := ToTime(args[0])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args[0].TypeName())
		}
		t2, ok := ToTime(args[1])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "time", args[1].TypeName())
		}

		ret = fn(t1, t2)
		return
	}
}

// funcPTiiiRO is a generated function to make charlang.CallableFunc.
// Source: funcPTiiiRO(t *Time, i1 int, i2 int, i3 int) (ret charlang.Object)
func funcPTiiiRO(fn func(*Time, int, int, int) charlang.Object) charlang.CallableFunc {
	return func(args ...charlang.Object) (ret charlang.Object, err error) {
		if len(args) != 4 {
			return charlang.Undefined, charlang.ErrWrongNumArguments.NewError("want=4 got=" + strconv.Itoa(len(args)))
		}

		t, ok := ToTime(args[0])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args[0].TypeName())
		}
		i1, ok := charlang.ToGoInt(args[1])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "int", args[1].TypeName())
		}
		i2, ok := charlang.ToGoInt(args[2])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("3rd", "int", args[2].TypeName())
		}
		i3, ok := charlang.ToGoInt(args[3])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("4th", "int", args[3].TypeName())
		}

		ret = fn(t, i1, i2, i3)
		return
	}
}

// funcPTsRO is a generated function to make charlang.CallableFunc.
// Source: funcPTsRO(t *Time, s string) (ret charlang.Object)
func funcPTsRO(fn func(*Time, string) charlang.Object) charlang.CallableFunc {
	return func(args ...charlang.Object) (ret charlang.Object, err error) {
		if len(args) != 2 {
			return charlang.Undefined, charlang.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		t, ok := ToTime(args[0])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args[0].TypeName())
		}
		s, ok := charlang.ToGoString(args[1])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "string", args[1].TypeName())
		}

		ret = fn(t, s)
		return
	}
}

// funcPTb2sRO is a generated function to make charlang.CallableFunc.
// Source: funcPTb2sRO(t *Time, b []byte, s string) (ret charlang.Object)
func funcPTb2sRO(fn func(*Time, []byte, string) charlang.Object) charlang.CallableFunc {
	return func(args ...charlang.Object) (ret charlang.Object, err error) {
		if len(args) != 3 {
			return charlang.Undefined, charlang.ErrWrongNumArguments.NewError("want=3 got=" + strconv.Itoa(len(args)))
		}

		t, ok := ToTime(args[0])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args[0].TypeName())
		}
		b, ok := charlang.ToGoByteSlice(args[1])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "bytes", args[1].TypeName())
		}
		s, ok := charlang.ToGoString(args[2])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("3rd", "string", args[2].TypeName())
		}

		ret = fn(t, b, s)
		return
	}
}

// funcPTLRO is a generated function to make charlang.CallableFunc.
// Source: funcPTLRO(t *Time, loc *Location) (ret charlang.Object)
func funcPTLRO(fn func(*Time, *Location) charlang.Object) charlang.CallableFunc {
	return func(args ...charlang.Object) (ret charlang.Object, err error) {
		if len(args) != 2 {
			return charlang.Undefined, charlang.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		t, ok := ToTime(args[0])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("1st", "time", args[0].TypeName())
		}
		loc, ok := ToLocation(args[1])
		if !ok {
			return charlang.Undefined, charlang.NewArgumentTypeError("2nd", "location", args[1].TypeName())
		}

		ret = fn(t, loc)
		return
	}
}
