/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "chardll.go"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern char *QuickRunChar(char *codeA, char *paramA, char *secureCodeA, char *injectA, char *globalsA, char *comBufA);

static void SayHello(char* s) {
	char *buf;

	buf = (char *) malloc(1 + 4 + 65536*256 + 1);
	
	QuickRunChar("a", "b", "c", "d", "e", buf);
	
    printf("%s\n", s);

    printf("0: %d\n", buf[0]);

    puts("_");

    printf("1: %d\n", buf[1]);

    puts("_");

	printf("2: %d\n", buf[2]);
	
    puts("_");

	printf("3: %d\n", buf[3]);
	
    puts("_");

	printf("4: %d\n", buf[4]);
	
    puts("_");
	
	int lenT = buf[1] * 65536 * 256 + buf[2] * 65536 + buf[3] * 256 + buf[4];

	printf("len: %d\n", lenT);
	
    puts("_");

	printf("5: %s\n", buf+5);
	
    puts("_");

	printf("end: %d\n", buf[1+4+lenT]);
	
	free(buf);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern GoInt SumInt(GoInt a, GoInt b);
extern char* DebugBuiltins(void);
extern GoFloat64 SumFloat(GoFloat64 a, GoFloat64 b);
extern char* SumStr(char* a, char* b);
extern char* DealStr(char* strA, char* codeA);
extern char* QuickRunChar(char* codeA, char* paramA, char* secureCodeA, char* injectA, char* globalsA, char* comBufA);

#ifdef __cplusplus
}
#endif
